from datetime import datetime
from typing import Any, Dict, List, Optional
import uuid

from pydantic import BaseModel, ConfigDict, Field


class ColumnMappingConfig(BaseModel):
    """Configurable column mapping provided by the user or auto-detected."""
    revenue_column: Optional[str] = Field(default=None, description="Column containing revenue / sales / amount")
    date_column: Optional[str] = Field(default=None, description="Column containing transaction / order date")
    order_id_column: Optional[str] = Field(default=None, description="Column containing order / transaction ID")
    customer_id_column: Optional[str] = Field(default=None, description="Column containing customer / client ID")
    category_column: Optional[str] = Field(default=None, description="Column containing product category / department")
    product_column: Optional[str] = Field(default=None, description="Column containing product / item name")
    region_column: Optional[str] = Field(default=None, description="Column containing region / territory / country")


class DetectedColumnMapping(BaseModel):
    """The resolved column mapping with detection status and confidence."""
    revenue_column: Optional[str] = None
    date_column: Optional[str] = None
    order_id_column: Optional[str] = None
    customer_id_column: Optional[str] = None
    category_column: Optional[str] = None
    product_column: Optional[str] = None
    region_column: Optional[str] = None
    auto_detected: bool = Field(default=True, description="Whether mapping was automatically inferred")
    detected_roles: Dict[str, str] = Field(default_factory=dict, description="Mapped role to column name")


class KPIMetrics(BaseModel):
    """High-level summary KPIs suitable for dashboard scorecards."""
    total_revenue: float = Field(..., description="Total aggregated revenue across all records")
    total_orders: int = Field(..., description="Total number of orders or transactions")
    unique_customers: int = Field(..., description="Count of distinct customers")
    average_order_value: float = Field(..., description="Average revenue per order (AOV)")
    overall_growth_percentage: Optional[float] = Field(
        default=None,
        description="Latest month-over-month growth percentage where date data exists",
    )


class MonthlyRevenueItem(BaseModel):
    """Monthly revenue point suitable for React line/bar charts."""
    month: str = Field(..., description="Month in YYYY-MM format")
    revenue: float = Field(..., description="Revenue for the month")
    orders: int = Field(..., description="Number of orders in the month")
    growth_percentage: Optional[float] = Field(
        default=None,
        description="Month-over-month growth rate compared to prior month",
    )


class CategoryRevenueItem(BaseModel):
    """Category breakdown suitable for React bar/donut charts."""
    category: str = Field(..., description="Category name")
    revenue: float = Field(..., description="Total revenue for this category")
    percentage: float = Field(..., description="Share of total revenue as percentage (0-100)")


class RegionRevenueItem(BaseModel):
    """Regional breakdown suitable for React choropleth/bar charts."""
    region: str = Field(..., description="Region name")
    revenue: float = Field(..., description="Total revenue for this region")
    percentage: float = Field(..., description="Share of total revenue as percentage (0-100)")


class TopProductItem(BaseModel):
    """Top product entry suitable for leaderboards/tables."""
    product: str = Field(..., description="Product name or identifier")
    revenue: float = Field(..., description="Total sales generated by product")
    orders: int = Field(..., description="Frequency or order count")


class TopCustomerItem(BaseModel):
    """Top customer entry suitable for leaderboards/tables."""
    customer: str = Field(..., description="Customer identifier or name")
    revenue: float = Field(..., description="Total spending by customer")
    orders: int = Field(..., description="Total orders placed")


class BusinessAnalyticsResponse(BaseModel):
    """Complete structured JSON analytics payload designed for React charts."""
    dataset_id: uuid.UUID
    mapping: DetectedColumnMapping
    kpis: KPIMetrics
    revenue_by_month: List[MonthlyRevenueItem] = Field(default_factory=list)
    revenue_by_category: List[CategoryRevenueItem] = Field(default_factory=list)
    revenue_by_region: List[RegionRevenueItem] = Field(default_factory=list)
    top_products: List[TopProductItem] = Field(default_factory=list)
    top_customers: List[TopCustomerItem] = Field(default_factory=list)
    supported_metrics: List[str] = Field(default_factory=list, description="List of metrics available from the dataset")
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
